[build]
  publish = "dist"
  command = "bun install && bun run build"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--production=false"
  VITE_API_URL = "https://tasks-api-29km.onrender.com/api/v1"
  VITE_SOCKET_URL = "https://tasks-api-29km.onrender.com"
  VITE_APP_NAME = "Tasks"
  VITE_APP_DESCRIPTION = "Gestionnaire de tâches collaboratif"
  VITE_APP_VERSION = "1.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers pour la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"